name: Evo - Build and Push to ECR

on:
  workflow_call:
    outputs:
      image:
        description: "The image name"
        value: ${{ jobs.build_job.outputs.image }}
      tag:
        description: "The image tag"
        value: ${{ jobs.build_job.outputs.tag }}

permissions:
  id-token: write
  contents: read

jobs:
  build_job:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.parse_image_tag.outputs.image }}
      tag: ${{ steps.parse_image_tag.outputs.tag }}
    steps:
      - name: Get current datetime
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.OPS_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.OPS_AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{raw}}
            type=ref,event=branch,suffix=-${{ steps.datetime.outputs.datetime }}
            type=ref,event=pr

      - name: Assume the evolvco-ops role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.OPS_AWS_ACCOUNT_ID }}:role/evolvco-github-oidc-hub
          aws-region: ${{ vars.OPS_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.evo
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Parse image tag
        id: parse_image_tag
        env:
          IMAGE_METADATA: ${{ steps.build_and_push.outputs.metadata }}
        run: |
          image=$(echo ${IMAGE_METADATA} | jq -r '."image.name"' | cut -d',' -f1)
          tag=$(echo ${image} | cut -d':' -f2)
          echo "image=$image" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
